"""crear tabla ofertas

Revision ID: 143d961cacab
Revises: 4e50e569c197
Create Date: 2026-03-30 17:29:02.631198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143d961cacab'
down_revision = '4e50e569c197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('solicitud_id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('objeto', sa.String(length=255), nullable=True),
    sa.Column('alcance', sa.Text(), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impuestos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_ofertas_empresa_codigo')
    )
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ofertas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ofertas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ofertas_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ofertas_solicitud_id'))
        batch_op.drop_index(batch_op.f('ix_ofertas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_ofertas_cliente_id'))

    op.drop_table('ofertas')
    # ### end Alembic commands ###
