"""crear tablas objetivos de calidad

Revision ID: 26dbb0ebcd9c
Revises: cb70177de244
Create Date: 2026-03-11 11:35:22.606444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dbb0ebcd9c'
down_revision = 'cb70177de244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objetivos_calidad',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('indicador', sa.String(length=200), nullable=False),
    sa.Column('meta', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('frecuencia', sa.String(length=30), nullable=False),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('resultado_actual', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objetivos_calidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objetivos_calidad_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('seguimientos_objetivos_calidad',
    sa.Column('objetivo_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_seguimiento', sa.Date(), nullable=False),
    sa.Column('valor_obtenido', sa.String(length=100), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivos_calidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seguimientos_objetivos_calidad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seguimientos_objetivos_calidad_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimientos_objetivos_calidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seguimientos_objetivos_calidad_empresa_id'))

    op.drop_table('seguimientos_objetivos_calidad')
    with op.batch_alter_table('objetivos_calidad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objetivos_calidad_empresa_id'))

    op.drop_table('objetivos_calidad')
    # ### end Alembic commands ###
