"""crear tablas organigrama

Revision ID: 31929620ff26
Revises: adb412643c03
Create Date: 2026-03-10 22:21:36.255683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31929620ff26'
down_revision = 'adb412643c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal')
    op.drop_table('cargos')
    # ### end Alembic commands ###
