"""ajustes modelo documentacion iso

Revision ID: 319d137323cf
Revises: b58e97637191
Create Date: 2026-03-20 12:25:54.316712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319d137323cf'
down_revision = 'b58e97637191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_versiones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('version_actual',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('version_actual',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('documento_versiones', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('fecha_aprobacion')

    # ### end Alembic commands ###
