"""ajustes clientes y solicitudes

Revision ID: 4e50e569c197
Revises: 319d137323cf
Create Date: 2026-03-30 10:41:31.576362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e50e569c197'
down_revision = '319d137323cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('tipo_cliente',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_unique_constraint('uq_clientes_empresa_identificacion', ['empresa_id', 'identificacion'])

    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_cliente_id'), ['cliente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_cliente_id'))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clientes_empresa_identificacion', type_='unique')
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('tipo_cliente',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
