"""crear tabla procesos

Revision ID: 5f894503a3c6
Revises: 26dbb0ebcd9c
Create Date: 2026-03-11 12:31:52.446189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f894503a3c6'
down_revision = '26dbb0ebcd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procesos',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('alcance', sa.Text(), nullable=True),
    sa.Column('entradas', sa.Text(), nullable=True),
    sa.Column('salidas', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procesos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procesos_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procesos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procesos_empresa_id'))

    op.drop_table('procesos')
    # ### end Alembic commands ###
