"""crear tabla contratos

Revision ID: 6ec8a21640e3
Revises: 143d961cacab
Create Date: 2026-03-30 21:17:19.152536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec8a21640e3'
down_revision = '143d961cacab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos',
    sa.Column('oferta_id', sa.BigInteger(), nullable=False),
    sa.Column('solicitud_id', sa.BigInteger(), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('objeto', sa.String(length=255), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_contratos_empresa_codigo')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_oferta_id'), ['oferta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_solicitud_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_oferta_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_cliente_id'))

    op.drop_table('contratos')
    # ### end Alembic commands ###
