"""initial models

Revision ID: adb412643c03
Revises: 
Create Date: 2026-03-10 15:02:47.525662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb412643c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('fecha_inicio_plan', sa.Date(), nullable=True),
    sa.Column('fecha_fin_plan', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('clientes',
    sa.Column('tipo_cliente', sa.String(length=30), nullable=True),
    sa.Column('identificacion', sa.String(length=30), nullable=True),
    sa.Column('nombre_razon_social', sa.String(length=200), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_email', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('ensayos_catalogo',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_ensayo_catalogo_empresa_codigo')
    )
    with op.batch_alter_table('ensayos_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ensayos_catalogo_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('metodos',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('norma_referencia', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_vigencia', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_metodos_empresa_codigo')
    )
    with op.batch_alter_table('metodos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metodos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('permiso_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permiso')
    )
    op.create_table('sedes',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sedes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('ensayo_metodos',
    sa.Column('ensayo_id', sa.BigInteger(), nullable=False),
    sa.Column('metodo_id', sa.BigInteger(), nullable=False),
    sa.Column('predeterminado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ensayo_id'], ['ensayos_catalogo.id'], ),
    sa.ForeignKeyConstraint(['metodo_id'], ['metodos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ensayo_id', 'metodo_id', name='uq_ensayo_metodo')
    )
    with op.batch_alter_table('ensayo_metodos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ensayo_metodos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('metodo_parametros',
    sa.Column('metodo_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('tipo_dato', sa.String(length=30), nullable=True),
    sa.Column('limite_min', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('limite_max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['metodo_id'], ['metodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metodo_parametros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metodo_parametros_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('sede_id', sa.BigInteger(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_usuarios_empresa_email'),
    sa.UniqueConstraint('empresa_id', 'username', name='uq_usuarios_empresa_username')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('auditoria_logs',
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('tabla', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.BigInteger(), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('datos_antes', sa.JSON(), nullable=True),
    sa.Column('datos_despues', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_logs_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('auditorias',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo_auditoria', sa.String(length=50), nullable=False),
    sa.Column('alcance', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('auditor_lider_id', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auditor_lider_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_auditoria_empresa_codigo')
    )
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditorias_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('documentos',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('proceso', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('version_actual', sa.String(length=20), nullable=True),
    sa.Column('elaborado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elaborado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_documentos_empresa_codigo')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('equipos',
    sa.Column('sede_id', sa.BigInteger(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('serie', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('fecha_puesta_servicio', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('criticidad', sa.String(length=30), nullable=True),
    sa.Column('requiere_calibracion', sa.Boolean(), nullable=False),
    sa.Column('frecuencia_calibracion_meses', sa.Integer(), nullable=True),
    sa.Column('frecuencia_mantenimiento_meses', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_equipos_empresa_codigo')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('no_conformidades',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('fecha_detectada', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('impacto', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_nc_empresa_codigo')
    )
    with op.batch_alter_table('no_conformidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_no_conformidades_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('personal_competencias',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('competencia', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('fecha_evaluacion', sa.Date(), nullable=True),
    sa.Column('evaluado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['evaluado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_competencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_competencias_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('riesgos',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('proceso', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('probabilidad', sa.Integer(), nullable=True),
    sa.Column('impacto', sa.Integer(), nullable=True),
    sa.Column('nivel_riesgo', sa.Integer(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_riesgo_empresa_codigo')
    )
    with op.batch_alter_table('riesgos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riesgos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('solicitudes',
    sa.Column('cliente_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_solicitudes_empresa_codigo')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'rol_id', name='uq_usuario_rol')
    )
    op.create_table('auditoria_hallazgos',
    sa.Column('auditoria_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_hallazgo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('requisito_incumplido', sa.String(length=200), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_hallazgos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_hallazgos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('documento_versiones',
    sa.Column('documento_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_version', sa.Date(), nullable=False),
    sa.Column('cambios', sa.Text(), nullable=True),
    sa.Column('elaborado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('revisado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('aprobado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['elaborado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documento_versiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_versiones_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('equipo_calibraciones',
    sa.Column('equipo_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_calibracion', sa.Date(), nullable=False),
    sa.Column('fecha_proxima', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('certificado_numero', sa.String(length=100), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipo_calibraciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipo_calibraciones_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('equipo_documentos',
    sa.Column('equipo_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('fecha_documento', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipo_documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipo_documentos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('equipo_mantenimientos',
    sa.Column('equipo_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_mantenimiento', sa.String(length=50), nullable=False),
    sa.Column('fecha_mantenimiento', sa.Date(), nullable=False),
    sa.Column('fecha_proxima', sa.Date(), nullable=True),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipo_mantenimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipo_mantenimientos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('muestras',
    sa.Column('solicitud_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('codigo_cliente', sa.String(length=50), nullable=True),
    sa.Column('tipo_muestra', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('fecha_muestreo', sa.Date(), nullable=True),
    sa.Column('recibido_por_id', sa.BigInteger(), nullable=True),
    sa.Column('condicion_recepcion', sa.Text(), nullable=True),
    sa.Column('ubicacion_almacenamiento', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['recibido_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_interno', name='uq_muestras_empresa_codigo_interno')
    )
    with op.batch_alter_table('muestras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_muestras_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('acciones_correctivas',
    sa.Column('no_conformidad_id', sa.BigInteger(), nullable=True),
    sa.Column('hallazgo_id', sa.BigInteger(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('causa_raiz', sa.Text(), nullable=True),
    sa.Column('plan_accion', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_compromiso', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('eficaz', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['auditoria_hallazgos.id'], ),
    sa.ForeignKeyConstraint(['no_conformidad_id'], ['no_conformidades.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_ac_empresa_codigo')
    )
    with op.batch_alter_table('acciones_correctivas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acciones_correctivas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('cadena_custodia',
    sa.Column('muestra_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('responsable_entrega', sa.String(length=150), nullable=True),
    sa.Column('responsable_recibe', sa.String(length=150), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['muestra_id'], ['muestras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cadena_custodia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cadena_custodia_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('documento_aprobaciones',
    sa.Column('documento_version_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('fecha_accion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['documento_version_id'], ['documento_versiones.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documento_aprobaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documento_aprobaciones_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('muestra_ensayos',
    sa.Column('muestra_id', sa.BigInteger(), nullable=False),
    sa.Column('ensayo_id', sa.BigInteger(), nullable=False),
    sa.Column('metodo_id', sa.BigInteger(), nullable=False),
    sa.Column('analista_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ensayo_id'], ['ensayos_catalogo.id'], ),
    sa.ForeignKeyConstraint(['metodo_id'], ['metodos.id'], ),
    sa.ForeignKeyConstraint(['muestra_id'], ['muestras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('muestra_ensayos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_muestra_ensayos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('resultados',
    sa.Column('muestra_ensayo_id', sa.BigInteger(), nullable=False),
    sa.Column('parametro_id', sa.BigInteger(), nullable=False),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_numero', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('cumple', sa.Boolean(), nullable=True),
    sa.Column('incertidumbre', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('limite_deteccion', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aprobado_por_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['muestra_ensayo_id'], ['muestra_ensayos.id'], ),
    sa.ForeignKeyConstraint(['parametro_id'], ['metodo_parametros.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['revisado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultados_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultados_empresa_id'))

    op.drop_table('resultados')
    with op.batch_alter_table('muestra_ensayos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_muestra_ensayos_empresa_id'))

    op.drop_table('muestra_ensayos')
    with op.batch_alter_table('documento_aprobaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_aprobaciones_empresa_id'))

    op.drop_table('documento_aprobaciones')
    with op.batch_alter_table('cadena_custodia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cadena_custodia_empresa_id'))

    op.drop_table('cadena_custodia')
    with op.batch_alter_table('acciones_correctivas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acciones_correctivas_empresa_id'))

    op.drop_table('acciones_correctivas')
    with op.batch_alter_table('muestras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_muestras_empresa_id'))

    op.drop_table('muestras')
    with op.batch_alter_table('equipo_mantenimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipo_mantenimientos_empresa_id'))

    op.drop_table('equipo_mantenimientos')
    with op.batch_alter_table('equipo_documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipo_documentos_empresa_id'))

    op.drop_table('equipo_documentos')
    with op.batch_alter_table('equipo_calibraciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipo_calibraciones_empresa_id'))

    op.drop_table('equipo_calibraciones')
    with op.batch_alter_table('documento_versiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documento_versiones_empresa_id'))

    op.drop_table('documento_versiones')
    with op.batch_alter_table('auditoria_hallazgos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_hallazgos_empresa_id'))

    op.drop_table('auditoria_hallazgos')
    op.drop_table('usuario_roles')
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_empresa_id'))

    op.drop_table('solicitudes')
    with op.batch_alter_table('riesgos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riesgos_empresa_id'))

    op.drop_table('riesgos')
    with op.batch_alter_table('personal_competencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_competencias_empresa_id'))

    op.drop_table('personal_competencias')
    with op.batch_alter_table('no_conformidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_no_conformidades_empresa_id'))

    op.drop_table('no_conformidades')
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_empresa_id'))

    op.drop_table('equipos')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_empresa_id'))

    op.drop_table('documentos')
    with op.batch_alter_table('auditorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditorias_empresa_id'))

    op.drop_table('auditorias')
    with op.batch_alter_table('auditoria_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_logs_empresa_id'))

    op.drop_table('auditoria_logs')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('metodo_parametros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metodo_parametros_empresa_id'))

    op.drop_table('metodo_parametros')
    with op.batch_alter_table('ensayo_metodos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ensayo_metodos_empresa_id'))

    op.drop_table('ensayo_metodos')
    with op.batch_alter_table('sedes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sedes_empresa_id'))

    op.drop_table('sedes')
    op.drop_table('rol_permisos')
    with op.batch_alter_table('metodos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metodos_empresa_id'))

    op.drop_table('metodos')
    with op.batch_alter_table('ensayos_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ensayos_catalogo_empresa_id'))

    op.drop_table('ensayos_catalogo')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_empresa_id'))

    op.drop_table('clientes')
    op.drop_table('roles')
    op.drop_table('permisos')
    op.drop_table('empresas')
    # ### end Alembic commands ###
