"""crear tabla riesgos_oportunidades

Revision ID: b58e97637191
Revises: 5f894503a3c6
Create Date: 2026-03-11 18:19:35.501561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58e97637191'
down_revision = '5f894503a3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riesgos_oportunidades',
    sa.Column('proceso_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('causa', sa.Text(), nullable=True),
    sa.Column('efecto', sa.Text(), nullable=True),
    sa.Column('probabilidad', sa.Integer(), nullable=False),
    sa.Column('impacto', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Text(), nullable=True),
    sa.Column('responsable_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha_compromiso', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riesgos_oportunidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riesgos_oportunidades_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riesgos_oportunidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riesgos_oportunidades_empresa_id'))

    op.drop_table('riesgos_oportunidades')
    # ### end Alembic commands ###
