"""agregar contrato a muestras

Revision ID: c5268fd3ae4c
Revises: 6ec8a21640e3
Create Date: 2026-03-30 22:07:02.893878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5268fd3ae4c'
down_revision = '6ec8a21640e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_muestras_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_foreign_key(None, 'contratos', ['contrato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_muestras_contrato_id'))
        batch_op.drop_column('contrato_id')

    # ### end Alembic commands ###
