"""agregar contenido a documento_versiones

Revision ID: cb70177de244
Revises: 31929620ff26
Create Date: 2026-03-11 10:34:58.570431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb70177de244'
down_revision = '31929620ff26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_versiones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_versiones', schema=None) as batch_op:
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
