"""contrato obligatorio en muestras

Revision ID: d1ed21cdfc92
Revises: c5268fd3ae4c
Create Date: 2026-03-30 22:43:40.269901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ed21cdfc92'
down_revision = 'c5268fd3ae4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestras', schema=None) as batch_op:
        batch_op.alter_column('contrato_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestras', schema=None) as batch_op:
        batch_op.alter_column('contrato_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
